`include "FPGA_POR.v"
`include "RAM128.v"
`include "RAM256.v"
`include "RAM4096.v"
`include "__user_project_wrapper.v"
// `include "user_project_sram_example.v"
`include "user_proj_example.v"
`include "caravel.v"
`include "caravel_clocking.v"
`include "caravel_core.v"
// `include "caravel_netlists.v"
`include "chip_io_FPGA.v"
`include "clock_div.v"
`include "debug_regs.v"
`include "defines.v"
`include "gpio_control_block.v"
`include "gpio_defaults_block.v"
`include "gpio_logic_high.v"
`include "housekeeping.v"
`include "housekeeping_spi.v"
`include "io_buf.v"
`include "mgmt_core.v"
`include "mgmt_core_wrapper.v"
`include "mgmt_protect.v"
`include "mgmt_protect_hv.v"
`include "mprj2_logic_high.v"
`include "mprj_io_buffer.v"
`include "mprj_logic_high.v"
`include "pads.v"
`include "user_defines.v"
`include "user_id_programming.v"
// original 16 word cache 
//`include "../../mgmt_soc/src/VexRiscv_MinDebugCache.v"
`include "../../arty/uart_to_spi.v"
//new cores being tested (in order of size) 
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_32Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_64Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_128Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_256Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_512Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_1024Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_2048Word.v"
//`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_4096Word.v"
`include "../../mgmt_soc/src/cache_changes_testing/VexRiscv_MinDebug_8192Word.v"
